# -*- coding: utf-8 -*-
"""Le opzioni pasto del piano denso (revisione 3, settembre 2026).

Qui si scrivono solo ingredienti e grammi: kcal, macro e peso del piatto li
calcola build_app.py partendo da foods.py. L'etichetta ("densa", "media",
"voluminosa", "liquida") è quella del PDF e serve per filtrare.

I nomi degli ingredienti devono coincidere con quelli in foods.py.
"""

ETICHETTE = {
    "densa": "Poco volume, molte calorie. Quando sei già pieno dal pasto prima.",
    "media": "Ingombro normale. Il default.",
    "voluminosa": "Piatto grande, sazia molto. Quando hai fame vera.",
    "liquida": "Si beve. Quando non hai fame per niente.",
}


def O(lab, n, nota, *items):
    return {"lab": lab, "n": n, "nota": nota, "items": list(items)}


MEALS = {
    "colazione": [
        O("densa", "Yogurt greco, avena e burro d'arachidi",
          "La più densa del gruppo. Una scodella sola, si prepara in due minuti.",
          ("Yogurt greco 0%", 170), ("Fiocchi d'avena", 50), ("Burro d'arachidi", 25),
          ("Miele", 15), ("Banana", 60)),
        O("liquida", "Frullato completo",
          "Si beve. Quando non hai fame la mattina, questa entra comunque.",
          ("Latte intero", 250), ("Proteine in polvere", 30), ("Fiocchi d'avena", 30),
          ("Burro d'arachidi", 15), ("Banana", 80)),
        O("densa", "Skyr e granola",
          "Zero preparazione, si assembla nella ciotola.",
          ("Skyr", 200), ("Granola", 60), ("Mandorle", 15), ("Frutti di bosco", 60)),
        O("densa", "Fette, burro d'arachidi e yogurt",
          "Vicina a quello che mangiavi prima, con le proteine sistemate.",
          ("Fette biscottate integrali", 50), ("Burro d'arachidi", 32), ("Miele", 15),
          ("Yogurt greco 0%", 160)),
        O("media", "Porridge proteico",
          "Caldo. Tre minuti in microonde.",
          ("Fiocchi d'avena", 60), ("Latte intero", 200), ("Proteine in polvere", 20),
          ("Burro d'arachidi", 18)),
        O("media", "Uova e avocado",
          "Salata e saziante senza essere ingombrante.",
          ("Uovo intero", 140), ("Pane bianco", 85), ("Avocado", 65), ("Pomodori", 80)),
        O("media", "Pane, salmone e spalmabile",
          "Nessuna cottura. Molto sale, non tutti i giorni.",
          ("Pane bianco", 100), ("Salmone affumicato", 80), ("Formaggio spalmabile", 45)),
        O("media", "Pane e primosale",
          "Se la mattina non vuoi niente di dolce.",
          ("Pane bianco", 90), ("Primosale", 90), ("Olive verdi", 25), ("Pomodori", 100)),
        O("voluminosa", "Ricotta e pane",
          "Quella che facevi: la tengo ma è la più ingombrante. Usala nei giorni di fame vera.",
          ("Ricotta vaccina", 150), ("Pane integrale", 100), ("Marmellata rid. zuccheri", 20),
          ("Yogurt greco 0%", 80)),
        O("media", "Pane e bresaola",
          "La più proteica. Utile se sai che il pranzo sarà fuori e scarso.",
          ("Pane bianco", 100), ("Bresaola", 70), ("Formaggio spalmabile", 30), ("Mandorle", 15)),
        O("media", "Kefir, granola e frutti di bosco",
          "Fresca e acidula. Nessuna preparazione.",
          ("Kefir", 250), ("Granola", 55), ("Proteine in polvere", 15), ("Mandorle", 12),
          ("Frutti di bosco", 60)),
        O("media", "Pane, ricotta e miele",
          "Dolce ma non stucchevole. Due minuti.",
          ("Pane bianco", 70), ("Ricotta vaccina", 150), ("Miele", 15), ("Proteine in polvere", 15)),
        O("media", "Toast prosciutto e mozzarella",
          "In padella o in tostiera, 4 minuti.",
          ("Pane bianco", 95), ("Prosciutto cotto", 60), ("Mozzarella", 55), ("Pomodori", 60)),
        O("densa", "Yogurt, cioccolato e pistacchi",
          "Sembra un dessert. Zero cottura.",
          ("Yogurt greco 5%", 200), ("Cioccolato fondente", 20), ("Pistacchi", 25),
          ("Miele", 12), ("Proteine in polvere", 12)),
        O("liquida", "Frullato al cioccolato",
          "Se il frullato semplice ti ha già stufato.",
          ("Latte intero", 300), ("Proteine in polvere", 30), ("Cioccolato fondente", 18),
          ("Banana", 110), ("Fiocchi d'avena", 12)),
        O("densa", "Pane e burro di mandorle",
          "Alternativa al burro d'arachidi, più delicata.",
          ("Pane bianco", 70), ("Crema di mandorle", 30), ("Banana", 80), ("Yogurt greco 0%", 170)),
        O("media", "Uova sode e pane",
          "Le uova si bollono una volta per tre giorni.",
          ("Uovo intero", 165), ("Pane bianco", 100), ("Olive verdi", 20), ("Pomodori", 80)),
        O("densa", "Skyr, semi e datteri",
          "I semi di zucca portano proteine dove non te le aspetti.",
          ("Skyr", 200), ("Semi di zucca", 25), ("Datteri", 55), ("Semi di chia", 12),
          ("Crema di mandorle", 12)),
        O("media", "Segale e salmone affumicato",
          "Salata e raffinata. Nessuna cottura.",
          ("Pane di segale", 110), ("Salmone affumicato", 80), ("Formaggio spalmabile", 50)),
        O("densa", "Porridge cioccolato e arachidi",
          "Caldo, 3 minuti in microonde.",
          ("Fiocchi d'avena", 55), ("Latte intero", 180), ("Cioccolato fondente", 15),
          ("Burro d'arachidi", 20), ("Proteine in polvere", 12)),
    ],
    "pranzo": [
        O("densa", "Pasta al tonno",
          "Il tonno all'olio invece che al naturale: stesso peso, 90 kcal in più.",
          ("Pasta di semola cruda", 100), ("Tonno sott'olio sgocc.", 110), ("Pomodori", 180)),
        O("media", "Pollo, riso e verdure",
          "Il riferimento, con la verdura ridotta a 150 g.",
          ("Petto di pollo crudo", 150), ("Riso bianco crudo", 92), ("Verdure cotte miste", 150),
          ("Olio EVO", 10)),
        O("densa", "Pasta al pesto con pollo",
          "La più densa. Un piatto piccolo che vale 620 kcal.",
          ("Pasta di semola cruda", 88), ("Petto di pollo crudo", 120), ("Pesto", 25),
          ("Grana Padano", 10)),
        O("densa", "Salmone e riso",
          "Olio quasi zero: il grasso è nel pesce.",
          ("Salmone fresco", 140), ("Riso bianco crudo", 80), ("Verdure cotte miste", 150),
          ("Olio EVO", 4)),
        O("media", "Tacchino e cous cous",
          "Il cous cous si fa in 5 minuti con l'acqua bollente.",
          ("Petto di tacchino crudo", 150), ("Cous cous crudo", 88), ("Verdure cotte miste", 150),
          ("Olio EVO", 10)),
        O("media", "Manzo e riso",
          "Massimo 2-3 volte a settimana.",
          ("Manzo magro crudo", 150), ("Riso bianco crudo", 88), ("Verdure cotte miste", 150),
          ("Olio EVO", 8)),
        O("densa", "Uova, pane e avocado",
          "3 uova. Zero cottura oltre alla padella.",
          ("Uovo intero", 165), ("Pane bianco", 80), ("Avocado", 70), ("Insalata mista", 100)),
        O("media", "Gamberi e cous cous",
          "Gamberi surgelati, 5 minuti in padella.",
          ("Gamberi", 180), ("Cous cous crudo", 88), ("Verdure cotte miste", 150), ("Olio EVO", 10)),
        O("voluminosa", "Merluzzo e patate",
          "La più ingombrante. Tienila per i giorni di fame.",
          ("Merluzzo fresco", 200), ("Patate", 350), ("Verdure cotte miste", 150), ("Olio EVO", 12)),
        O("voluminosa", "Ceci e tonno",
          "Zero cottura, tutto da dispensa. Record di fibra.",
          ("Ceci in scatola sgocc.", 200), ("Tonno sott'olio sgocc.", 90), ("Pane bianco", 40),
          ("Insalata mista", 100), ("Olio EVO", 5)),
        O("densa", "Piadina con pollo",
          "Si mangia in mano. 8 minuti.",
          ("Piadina", 115), ("Petto di pollo crudo", 140), ("Formaggio spalmabile", 25),
          ("Insalata mista", 60)),
        O("densa", "Riso, tonno e olive",
          "Buono anche freddo il giorno dopo.",
          ("Riso bianco crudo", 100), ("Tonno sott'olio sgocc.", 110), ("Olive verdi", 25),
          ("Pomodori", 100)),
        O("media", "Gnocchi al pesto con pollo",
          "Gli gnocchi cuociono in 2 minuti.",
          ("Gnocchi di patate", 210), ("Pesto", 22), ("Grana Padano", 15), ("Petto di pollo crudo", 100)),
        O("voluminosa", "Insalata di ceci e feta",
          "Zero cottura, tutto da dispensa e frigo.",
          ("Ceci in scatola sgocc.", 160), ("Feta", 60), ("Uovo intero", 110), ("Pomodori", 120),
          ("Olio EVO", 6)),
        O("densa", "Pasta alle alici",
          "Saporita. Le alici stanno in dispensa.",
          ("Pasta di semola cruda", 100), ("Alici sott'olio sgocc.", 55), ("Pomodori", 150),
          ("Grana Padano", 15), ("Olio EVO", 6)),
        O("densa", "Orzo, salmone e avocado",
          "Freddo, si porta anche fuori.",
          ("Orzo perlato crudo", 90), ("Salmone affumicato", 100), ("Avocado", 55), ("Pomodori", 80)),
        O("densa", "Wrap tonno e avocado",
          "Zero cottura, si arrotola e via.",
          ("Tortilla di grano", 110), ("Tonno al naturale sgocc.", 130), ("Avocado", 70),
          ("Insalata mista", 60)),
        O("media", "Farro, pollo e pomodori secchi",
          "I pomodori secchi cambiano completamente il gusto.",
          ("Farro perlato crudo", 95), ("Petto di pollo crudo", 140), ("Pomodori secchi", 25),
          ("Olio EVO", 7)),
        O("media", "Tortellini e pollo",
          "Quando volete mangiare la stessa cosa in due.",
          ("Tortellini freschi", 130), ("Petto di pollo crudo", 80), ("Grana Padano", 12),
          ("Insalata mista", 100), ("Olio EVO", 6)),
        O("media", "Polenta e primosale",
          "Confortante. La polenta istantanea in 5 minuti.",
          ("Polenta istantanea", 60), ("Primosale", 100), ("Uovo intero", 55),
          ("Verdure cotte miste", 150), ("Olio EVO", 3)),
    ],
    "spuntino": [
        O("liquida", "Frullato proteico",
          "Due minuti, si beve guidando. Quando arriva la whey diventa la tua opzione principale.",
          ("Latte intero", 250), ("Proteine in polvere", 28), ("Burro d'arachidi", 15)),
        O("densa", "Yogurt, burro d'arachidi e miele",
          "Un vasetto e un cucchiaio. Il minimo ingombro possibile a queste calorie.",
          ("Yogurt greco 0%", 170), ("Burro d'arachidi", 32), ("Miele", 12)),
        O("densa", "Skyr e datteri",
          "Dolce e compatta. I datteri si portano ovunque.",
          ("Skyr", 200), ("Datteri", 50), ("Mandorle", 15)),
        O("media", "Bresaola e panino",
          "Si compra al bar. Chiedi il panino con la bresaola e basta.",
          ("Bresaola", 80), ("Pane bianco", 60), ("Mela", 130)),
        O("liquida", "Frullato UHT e mandorle",
          "Tutto acquistabile al supermercato o in autogrill, niente da preparare.",
          ("Frullato proteico UHT", 330), ("Mandorle", 20), ("Banana", 100)),
        O("densa", "Grana, pane e fichi",
          "Compatta e a lunga conservazione. Vive nello zaino.",
          ("Grana Padano", 35), ("Pane bianco", 45), ("Fichi secchi", 35)),
        O("media", "Tonno e gallette",
          "Tutto da dispensa, si apre senza posate.",
          ("Tonno al naturale sgocc.", 120), ("Gallette di riso", 30), ("Mandorle", 15),
          ("Pomodori", 100)),
        O("densa", "Barretta e frutta secca",
          "La più tascabile. Barretta con almeno 20 g di proteine e meno di 10 g di zuccheri.",
          ("Barretta proteica", 60), ("Mandorle", 10), ("Mela", 130)),
        O("media", "Fiocchi di latte e noci",
          "Se ti va qualcosa da masticare invece che da bere.",
          ("Fiocchi di latte", 150), ("Noci", 20), ("Datteri", 30)),
        O("liquida", "Latte, whey e banana",
          "La più leggera sullo stomaco. Buona subito dopo l'allenamento.",
          ("Latte intero", 250), ("Proteine in polvere", 25), ("Banana", 110)),
        O("densa", "Yogurt, cioccolato e pistacchi",
          "La più golosa del gruppo.",
          ("Yogurt greco 5%", 170), ("Cioccolato fondente", 18), ("Pistacchi", 20)),
        O("media", "Pane, hummus e bresaola",
          "Zero cottura, si assembla in un minuto.",
          ("Pane bianco", 50), ("Hummus", 50), ("Bresaola", 60)),
        O("media", "Kefir e granola",
          "Leggera sullo stomaco.",
          ("Kefir", 250), ("Granola", 30), ("Proteine in polvere", 15), ("Mandorle", 5)),
        O("densa", "Skyr e burro di mandorle",
          "Due ingredienti, un cucchiaio.",
          ("Skyr", 200), ("Crema di mandorle", 31), ("Miele", 10)),
        O("densa", "Wasa, spalmabile e salmone",
          "Croccante e salata. Ingombro minimo.",
          ("Wasa croccante integrale", 38), ("Formaggio spalmabile", 45), ("Salmone affumicato", 60)),
        O("liquida", "Frullato UHT e anacardi",
          "Tutto comprato, niente da preparare.",
          ("Frullato proteico UHT", 330), ("Anacardi", 25), ("Banana", 60)),
        O("media", "Uova sode e grissini",
          "Da preparare la sera prima.",
          ("Uovo intero", 110), ("Grissini", 30), ("Pomodori", 100), ("Grana Padano", 15)),
        O("densa", "Ricotta, miele e noci",
          "La ricotta torna, ma in porzione piccola.",
          ("Ricotta vaccina", 150), ("Miele", 15), ("Noci", 8), ("Proteine in polvere", 10)),
        O("media", "Sgombro e gallette",
          "Lo sgombro ha più omega-3 del tonno.",
          ("Sgombro al naturale sgocc.", 100), ("Gallette di riso", 35), ("Mandorle", 5),
          ("Pomodori", 100)),
        O("liquida", "Frullato con chia",
          "La chia aggiunge fibra dove ne manca.",
          ("Latte intero", 200), ("Proteine in polvere", 25), ("Banana", 100), ("Semi di chia", 10)),
    ],
    "cena": [
        O("densa", "Salmone e riso",
          "1-2 volte a settimana. Poco piatto, molte calorie.",
          ("Salmone fresco", 150), ("Riso bianco crudo", 65), ("Verdure cotte miste", 150),
          ("Olio EVO", 4)),
        O("densa", "Tonno all'olio e pane",
          "Zero cottura. Cinque minuti in tutto.",
          ("Tonno sott'olio sgocc.", 130), ("Pane bianco", 90), ("Pomodori", 150), ("Olio EVO", 5)),
        O("media", "Pollo e riso",
          "Se a pranzo hai mangiato pesce.",
          ("Petto di pollo crudo", 150), ("Riso bianco crudo", 72), ("Verdure cotte miste", 150),
          ("Olio EVO", 12)),
        O("media", "Frittata e pane",
          "Dieci minuti.",
          ("Uovo intero", 110), ("Albume liquido", 120), ("Pane bianco", 80),
          ("Verdure cotte miste", 150), ("Olio EVO", 10)),
        O("densa", "Uova e avocado",
          "La più veloce in assoluto.",
          ("Uovo intero", 165), ("Avocado", 70), ("Pane bianco", 70), ("Insalata mista", 100)),
        O("media", "Primosale e pane",
          "Serata pigra, nessuna cottura.",
          ("Primosale", 110), ("Pane bianco", 80), ("Verdure cotte miste", 150), ("Olio EVO", 4)),
        O("media", "Gamberi e cous cous",
          "Surgelati vanno benissimo.",
          ("Gamberi", 180), ("Cous cous crudo", 78), ("Verdure cotte miste", 150), ("Olio EVO", 10)),
        O("media", "Manzo e patate",
          "Tagli magri, non più di 2-3 volte a settimana.",
          ("Manzo magro crudo", 150), ("Patate", 300), ("Verdure cotte miste", 150), ("Olio EVO", 8)),
        O("voluminosa", "Pesce bianco e patate",
          "La più ingombrante. Solo se hai fame vera.",
          ("Merluzzo fresco", 200), ("Patate", 240), ("Insalata mista", 120), ("Pane bianco", 40),
          ("Olio EVO", 12)),
        O("voluminosa", "Lenticchie e uova",
          "La sera vegetariana. I legumi da soli non bastano.",
          ("Lenticchie in scatola sgocc.", 200), ("Uovo intero", 110), ("Verdure cotte miste", 150),
          ("Pane bianco", 40), ("Olio EVO", 6)),
        O("densa", "Wrap di tacchino",
          "8 minuti. Si mangia in mano.",
          ("Tortilla di grano", 105), ("Petto di tacchino crudo", 150), ("Formaggio spalmabile", 30),
          ("Insalata mista", 60)),
        O("media", "Insalatona con feta e uova",
          "Zero cottura oltre alle uova.",
          ("Uovo intero", 110), ("Feta", 60), ("Insalata mista", 120), ("Pomodori", 100),
          ("Pane bianco", 60), ("Olio EVO", 5)),
        O("densa", "Sgombro e patate",
          "Lo sgombro in scatola non richiede cottura.",
          ("Sgombro al naturale sgocc.", 130), ("Patate", 300), ("Verdure cotte miste", 150),
          ("Olio EVO", 6)),
        O("densa", "Riso al salmone affumicato",
          "Buono anche tiepido.",
          ("Riso bianco crudo", 75), ("Salmone affumicato", 110), ("Avocado", 55),
          ("Verdure cotte miste", 100)),
        O("media", "Piadina e primosale",
          "Serata pigra, 5 minuti.",
          ("Piadina", 75), ("Primosale", 110), ("Verdure cotte miste", 150), ("Pomodori", 80)),
        O("media", "Gnocchi al pomodoro con manzo",
          "Un piatto solo, cottura rapida.",
          ("Gnocchi di patate", 175), ("Manzo magro crudo", 130), ("Pomodori", 100),
          ("Grana Padano", 10), ("Olio EVO", 6)),
        O("densa", "Uova, hummus e pane",
          "Zero cottura se le uova sono già sode.",
          ("Uovo intero", 140), ("Hummus", 65), ("Pane bianco", 85), ("Insalata mista", 80)),
        O("densa", "Toast prosciutto e mozzarella",
          "La cena più veloce che esiste.",
          ("Pane bianco", 90), ("Prosciutto cotto", 65), ("Mozzarella", 60), ("Pomodori", 80)),
        O("media", "Polenta e formaggio",
          "Calda, per le sere fredde.",
          ("Polenta istantanea", 45), ("Primosale", 115), ("Uovo intero", 55),
          ("Verdure cotte miste", 150), ("Olio EVO", 3)),
        O("densa", "Pasta alle alici e olive",
          "Tutto da dispensa.",
          ("Pasta di semola cruda", 95), ("Alici sott'olio sgocc.", 55), ("Olive verdi", 25),
          ("Pomodori", 120), ("Grana Padano", 15)),
    ],
}

# Testo fisso della scheda Piano: regole che non cambiano con le opzioni.
REGOLE = [
    ("Giorno di riposo",
     "Riduci il carboidrato del pranzo di 20 g crudi e togli il pane, o 80 g di patate, dalla cena. "
     "Vieni a ~1.900 kcal. Le proteine restano intatte."),
    ("Il regolatore della fibra",
     "Scegliendo sempre le opzioni dense scendi intorno ai 18-19 g di fibra. Almeno un pasto al giorno "
     "voluminoso o medio con verdura, oppure un frutto o 10 g di semi di chia. 22-25 g vanno bene."),
    ("Se una giornata va storta",
     "Non forzarti a finire: se un piatto non entra, lascia il carboidrato. Finisci la fonte proteica, "
     "è l'unica cosa che non si recupera il giorno dopo. Sotto i 120 g di proteine uno shaker da 30 g "
     "risolve. Non compensare il giorno dopo."),
    ("Alcol",
     "1-2 drink, 1-2 volte a settimana. Distillato liscio ~70 kcal, calice di vino ~120, birra media "
     "~200, cocktail 300-400. Quel giorno togli la frutta secca dallo spuntino e 5 g di olio."),
    ("Integrazione",
     "Creatina monoidrato 3-5 g al giorno, sempre, orario indifferente. Omega-3 1-2 g a un pasto con "
     "grassi. Vitamina D3 solo dopo averla misurata. Proteine in polvere: la soluzione più economica "
     "delle barrette."),
]
